#!/usr/bin/env bash

echo -e "\n*** valid.bats ***\n"
./test/bats/bin/bats ./test/valid.bats
echo -e "\n*** encrypt.bats ***\n"
./test/bats/bin/bats ./test/encrypt.bats
echo -e "\n*** cesar.bats ***\n"
./test/bats/bin/bats ./test/cesar.bats
echo -e "\n*** enigma.bats ***\n"
./test/bats/bin/bats ./test/enigma.bats
